[package]
name = "tidesdb"
version = "0.10.0"
edition = "2024"
authors = ["TidesDB <hello@tidesdb.com>"]
description = "TidesDB is a high-performance embeddable, durable, adaptive, and optionally cloud-native key-value storage engine"
license = "MPL-2.0"
repository = "https://github.com/tidesdb/tidesdb-rs"
homepage = "https://tidesdb.com"
documentation = "https://tidesdb.com/reference/rust/"
readme = "README.md"
keywords = ["database", "key-value", "storage", "lsm-tree", "storageengine"]
categories = ["database", "data-structures"]

[dependencies]
libc = "0.2"
thiserror = "1.0"

[build-dependencies]
pkg-config = "0.3"
cmake = "0.1"
flate2 = "1"
tar = "0.4"
cfg-if = "1"
tidesdb-src-v9-0-0 = {version = "0.1", optional = true}
tidesdb-src-v9-0-1 = {version = "0.1", optional = true}
tidesdb-src-v9-0-2 = {version = "0.1", optional = true}
tidesdb-src-v9-0-3 = {version = "0.1", optional = true}
tidesdb-src-v9-0-4 = {version = "0.1", optional = true}
tidesdb-src-v9-0-5 = {version = "0.1", optional = true}
tidesdb-src-v9-0-6 = {version = "0.1", optional = true}
tidesdb-src-v9-0-7 = {version = "0.1", optional = true}
tidesdb-src-v9-0-8 = {version = "0.1", optional = true}
tidesdb-src-v9-0-9 = {version = "0.1", optional = true}
tidesdb-src-v9-1-0 = {version = "0.1", optional = true}
tidesdb-src-v9-2-0 = {version = "0.1", optional = true}
tidesdb-src-v9-2-1 = {version = "0.1", optional = true}
tidesdb-src-v9-2-2 = {version = "0.1", optional = true}
tidesdb-src-v9-2-3 = {version = "0.1", optional = true}
tidesdb-src-v9-2-4 = {version = "0.1", optional = true}
tidesdb-src-v9-2-5 = {version = "0.1", optional = true}
tidesdb-src-v9-3-0 = {version = "0.1", optional = true}
tidesdb-src-v9-3-1 = {version = "0.1", optional = true}
tidesdb-src-v9-3-2 = {version = "0.1", optional = true}
tidesdb-src-v9-3-3 = {version = "0.1", optional = true}
tidesdb-src-v9-3-4 = {version = "0.1", optional = true}
tidesdb-src-v9-3-5 = {version = "0.1", optional = true}

[dev-dependencies]
tempfile = "3.10"

[features]
default = ["v9_3_5"]
objectstore = []
v9_0_0 = ["dep:tidesdb-src-v9-0-0"]
v9_0_1 = ["dep:tidesdb-src-v9-0-1"]
v9_0_2 = ["dep:tidesdb-src-v9-0-2"]
v9_0_3 = ["dep:tidesdb-src-v9-0-3"]
v9_0_4 = ["dep:tidesdb-src-v9-0-4"]
v9_0_5 = ["dep:tidesdb-src-v9-0-5"]
v9_0_6 = ["dep:tidesdb-src-v9-0-6"]
v9_0_7 = ["dep:tidesdb-src-v9-0-7"]
v9_0_8 = ["dep:tidesdb-src-v9-0-8"]
v9_0_9 = ["dep:tidesdb-src-v9-0-9"]
v9_1_0 = ["dep:tidesdb-src-v9-1-0"]
v9_2_0 = ["dep:tidesdb-src-v9-2-0"]
v9_2_1 = ["dep:tidesdb-src-v9-2-1"]
v9_2_2 = ["dep:tidesdb-src-v9-2-2"]
v9_2_3 = ["dep:tidesdb-src-v9-2-3"]
v9_2_4 = ["dep:tidesdb-src-v9-2-4"]
v9_2_5 = ["dep:tidesdb-src-v9-2-5"]
v9_3_0 = ["dep:tidesdb-src-v9-3-0"]
v9_3_1 = ["dep:tidesdb-src-v9-3-1"]
v9_3_2 = ["dep:tidesdb-src-v9-3-2"]
v9_3_3 = ["dep:tidesdb-src-v9-3-3"]
v9_3_4 = ["dep:tidesdb-src-v9-3-4"]
v9_3_5 = ["dep:tidesdb-src-v9-3-5"]

[lib]
name = "tidesdb"
path = "src/lib.rs"
